AllCops:
  TargetRubyVersion: 3.0.2

Style/Documentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedColonStyle: table

Metrics/BlockLength:
  CountAsOne: [ 'array', 'heredoc', 'hash' ]
  IgnoredMethods:
    - context
    - it
    - describe

Style/Lambda:
  EnforcedStyle: literal
